---
title: "Final Data Creation"
author: "Dillon M. Smith"
date: "11/27/2018"
output: html_document
---

```{r setup, include=FALSE}
# load necessary libraries
library(knitr)
library(stringr)
library(fs)
library(haven)
library(sjlabelled)
library(lubridate)
library(readxl)
library(stargazer)
library(tidyverse)

# set up document settings
opts_chunk$set(echo = FALSE,
               message = FALSE,
               error = FALSE,
               warning = FALSE)
```

```{r load_data}
# read in winter Olympic data
winter <- read_csv("winter.csv")

# read in summer Olympic data
summer <- read_csv("summer.csv")

# hard code US Olympic Medal Ranks for all winter Olympics in winter.csv
winter_ranks <- c(5, 2, 1, 8, 4, 2, 6, 3, 8, 9, 5, 3, 3, 3, 9, 5, 5, 5, 3, 2, 3, 4)

# hard code US Olympic Medal Ranks for all summer Olympics in summer.csv
summer_ranks <- c(1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 3, 1, 3, 2, 1, 1, 1, 2, 1)

# read in presidential election data
presidential <- read_excel("presidential_turnouts.xls", 
                           skip = 1,
                           col_types = "numeric")

# read in midterm election data
midterm <- read_excel("midterm_turnouts.xls",
                      skip = 1)
```

```{r tidy_data}
# create elections dataframe combining presidential and midterm datasets
elections <- bind_rows(presidential, midterm, .id = "source") %>% 
  # arrange by year in ascending order
  arrange(YEAR) %>% 
  # mutate source variable to be easier to understand
  mutate(source = case_when(source == 1 ~ "presidential",
                            source == 2 ~ "midterm")) %>%
  # replace uppercase column names with lowercase
  rename_all(tolower) %>% 
  # rename % with percent
  rename(percent = "%") %>% 
  # create difference variable
  transform(percent_change = ave(percent, source, FUN = function(x) c(NA, diff(x))))

# create olympics dataframe combining winter and summer datasets
olympics <- bind_rows(summer, winter, .id = "source") %>% 
  # arrange by year un ascending order
  arrange(Year) %>% 
  # mutate source variable to be easier to understand
  mutate(source = case_when(source == 1 ~ "summer",
                            source == 2 ~ "winter")) %>% 
  # replace all uppercase column names with lowercase
  rename_all(tolower)

# create summary statistics for winter olympic medal counts
winter_total <- winter %>% 
  # lowercase column names
  rename_all(tolower) %>% 
  # group the data by year
  group_by(year) %>% 
  # count how many medals were awarded in each olympic games
  count(medal) %>% 
  # spread the data by medal type
  spread(key = medal, value = "n") %>% 
  # rename medal columns
  rename(total_gold = "Gold",
         total_silver = "Silver",
         total_bronze = "Bronze")

# create summary statistics for summer olympic medal counts
summer_total <- summer %>% 
  # lowercase column names
  rename_all(tolower) %>% 
  # group the data by year
  group_by(year) %>% 
  # count how many medals were awarded in each olympic games
  count(medal) %>% 
  # spread the data by medal type
  spread(key = medal, value = "n") %>% 
  # rename medal columns
  rename(total_gold = "Gold",
         total_silver = "Silver",
         total_bronze = "Bronze")

# create summary statistics for US winter olympic medal counts
winter_us <- winter %>% 
  # lowercase column names
  rename_all(tolower) %>% 
  # filter data for US results
  filter(country == "USA") %>% 
  # group the data by year
  group_by(year) %>% 
  # count how many medals were awarded in each olympic games
  count(medal) %>% 
  # spread the data by medal type
  spread(key = medal, value = "n", fill = 0) %>% 
  # rename medal columns
  rename(us_gold = "Gold",
         us_silver = "Silver",
         us_bronze = "Bronze")
# add hard coded US medal count rankings
winter_us$rank <- winter_ranks

# create summary statistics for US summer olympic medal counts
summer_us <- summer %>% 
  # lowercase column names
  rename_all(tolower) %>% 
  # filter data for US results
  filter(country == "USA") %>% 
  # group the data by year
  group_by(year) %>% 
  # count how many medals were awarded in each olympic games
  count(medal) %>% 
  # spread the data by medal type
  spread(key = medal, value = "n", fill = 0) %>% 
  # rename medal columns
  rename(us_gold = "Gold",
         us_silver = "Silver",
         us_bronze = "Bronze")
# add hard coded US medal count rankings
summer_us$rank <- summer_ranks
```

```{r join_data}
# create final winter data
winter_final <- left_join(winter_us, winter_total, by = "year") %>% 
  # create percent variables for gold and total medals
  mutate(gold_percent = round(us_gold/total_gold, 3),
         medal_percent = round((us_gold + us_silver + us_bronze) / (total_gold + total_silver + total_bronze), 3)) %>% 
  # create change variable for gold and total medals
  transform(gold_change = ave(gold_percent, FUN = function(x) c(NA, diff(x))),
            total_change = ave(medal_percent, FUN = function(x) c(NA, diff(x))))
# create final summer data
summer_final <- left_join(summer_us, summer_total, by = "year") %>% 
  # create percent variables for gold and total medals
  mutate(gold_percent = round(us_gold/total_gold, 3),
         medal_percent = round((us_gold + us_silver + us_bronze) / (total_gold + total_silver + total_bronze), 3)) %>% 
  # create change cariable for gold and total medals
  transform(gold_change = ave(gold_percent, FUN = function(x) c(NA, diff(x))),
            total_change = ave(medal_percent, FUN = function(x) c(NA, diff(x))))

# join winter data and elections data by year
winter_joined <- left_join(winter_final, elections, by = "year") %>% 
  # select important variables
  select(year, rank, gold_percent, gold_change, medal_percent, total_change, source, percent, percent_change) %>% 
  # select variables with voting data
  head(20)

# join summer data and elections data by year
summer_joined <- left_join(summer_final, elections, by = "year") %>% 
  # select important variables
  select(year, rank, gold_percent, gold_change, medal_percent, total_change, source, percent, percent_change) %>% 
  # select variables with voting data 
  head(25)

final_data <- bind_rows(winter_joined, summer_joined, .id = "olympics") %>% 
  arrange(year) %>% 
  mutate(olympics = case_when(olympics == 1 ~ "winter",
                              olympics == 2 ~ "summer"),
         gold_change = replace_na(gold_change, 0),
         total_change = replace_na(total_change, 0))
  
  
write_rds(final_data, "final_app/final_data.rds")
```

```{r create_lm}
# create linear model for percent
winter_lm <- glm(percent ~ rank + gold_percent + gold_change + medal_percent + total_change, 
                 data = winter_joined)
# create linear model for change in percent 
winter_lm_change <- glm(percent_change ~ rank + gold_percent + gold_change + medal_percent + total_change, 
                        data = winter_joined)
 
# create linear model for percent 
summer_lm <- glm(percent ~ rank + gold_percent + gold_change + medal_percent + total_change, 
                 data = summer_joined)
# create linear model for change in percent 
summer_lm_change <- glm(percent_change ~ rank + gold_percent + gold_change + medal_percent + total_change, 
                        data = summer_joined)
```

# Winter Data

```{r}
str(winter_joined)
```

# Winter Models

### Percent

```{r, results='asis'}
stargazer(winter_lm, type = "html")
```

### Change in Percent

```{r, results='asis'}
stargazer(winter_lm_change, type = "html")
```

# Summer Data

```{r}
str(summer_joined)
```

# Summer Models

### Percent

```{r, results='asis'}
stargazer(summer_lm, type = "html")
```

### Change in Percent

```{r, results='asis'}
stargazer(summer_lm_change, type = "html")
```
